
## 📚 숫자블록

### 📌 [문제링크](https://school.programmers.co.kr/learn/courses/30/lessons/12923#qna)

### 문제 해설

- 숫자 0이 설치된 블록에 다른 숫자가 적힌 블록을 다음규칙과 같이 설치하기로 결정했다.
- 블록 번호가 n 일 때 가장 첫 블록위치는 n * 2 부터 시작해서 n * 3, n * 4, ... 쭉 설치한다.
- 길이가 1,000,000,000인 도로에 1부터 10,000,000까지의 숫자가 적힌 블록들을 위의 규칙대로 설치한다.
- 구간의 시작 begin과 구간의 마지막 end가 매개변수로 주어 질 때, 해당 구간의 깔려 있는 블록의 숫자 배열을 return하는 문제이다.

### 문제 풀이

- 문제를 분석해보니 해당 수를 구성하는 약수중에 자기자신을 제외한 가장 큰 약수를 구하는 것이었다! 그러나 1은 약수를 하나를 가지고 가장 큰 약수가 자기자신인 예외처리를 하였다.

- 그러나 여기에 함정이 있다!! 문제를 자세히 읽어보면 숫자블록은 10,000,000번 블록까지 놓는다는 것이다. 다시말해 약수의 범위가 10,000,000번까지만 인정한다는 것이다.

- 요약 : 자기 자신을 제외한 가장 큰 약수구하기 (단, 약수의 범위가 10,000,000 이내인 경우이다. 초과할 경우 순차적으로 탐색하면서 범위내인 약수를 찾을것)

```
def solution(begin, end): # 다시풀기 다시풀기
    
    return [tile(num) for num in range(begin,end+1)]
    
def tile(num):
    if num == 1:
        return 0
    
    answer = 1
    for i in range(2, int(num**(1/2)+1)):
        if num % i == 0 :
            if num // i <= 1e7 : # 블록 조건 이하
                answer = num // i
                break
            else: # 블록이 10000000 넘었을때 작은 약수는 범위내인지 확인
                if i <= 1e7 :
                    answer = i
                else: #작은 약수도 범위 벗어나면 1 대입
                    answer = 1
                    
                continue
            
    return answer
```

자꾸 효율성 테스트에서 에러가 나길래 끙끙 고민을 하다가 구글링을 참고해서 다시 코드를 짰는데,, 

```
def solution(begin, end): # 다시풀기 다시풀기
    
    return [tile(num) for num in range(begin,end+1)]
    
def tile(num):
    if num == 1:
        return 0
    
    answer = 1
    for i in range(2, int(num**(1/2)+1)):
        if num % i == 0 :
            if num // i <= 1e7 : # 블록 조건 이하
                answer = num // i
                break
            else: # 블록이 10000000 넘었을때 작은 약수는 범위내인지 확인
                answer = 1
                continue
            
    return answer
```
이건 정답처리되었다. 근데 뭔가 좀 이상한 느낌이 들었다. 가장 큰 약수를 구하는건데 왜 약수를 다시 1로 처리하는지 이해가 되지 않았다. 나누어주어도 

프로그래머스 질문하기에 한 분이 작성해주신 반례를 참고하였다.

예를 들어, 932869174 이라는 수는
1, 2, 31, 62, 15046277, 30092554, 466434587, 932869174 를 약수로 가지는 수 이다. [참고링크](https://school.programmers.co.kr/questions/34268)

뒤의 932869174를 나눠준 3개의 몫은 범위를 초과하나 제수는 범위안에 있으므로 값을 저장해주어서 결국 답은 62가 되어야 한다. 
그러나 프로그래머스에서는 이런 테스트케이스를 고려하지 않은 것 같다.

2023/02/10 테스트케이스가 수정되어 다시 풀어보았다.

- 재풀이 (2023\/02\/10)

```
def solution(begin, end): # 다시풀기 다시풀기
    
    return [tile(num) for num in range(begin,end+1)]

def tile(num):
    if num == 1:
        return 0
    
    answer = 1

    for n in range(2, int(num**(1/2))+1 ):
        if num % n == 0:
            #print(f'{num}은 {n}으로 나뉘어지고 {n}과 {num//n}을 약수로 가진다 ')
            #if n == 62: print(n ,num//n)
            if num // n <= int(1e7):
                #print(num//n)
                answer = num // n
                break
            else:
                #print(n)
                answer = n
                continue
    #print(answer)
    return answer
```
